#ifndef PODIO_SCHEMAEVOLUTION_H
#define PODIO_SCHEMAEVOLUTION_H

#include <cstdint>
#include <functional>
#include <string>
#include <unordered_map>
#include <vector>

namespace podio {

enum class Backend { ROOT, SIO };

using SchemaVersionT = uint32_t;

struct CollectionReadBuffers;

class SchemaEvolution {
  using EvolutionFuncT = std::function<podio::CollectionReadBuffers(podio::CollectionReadBuffers, SchemaVersionT)>;
  using EvolFuncVersionMapT = std::vector<EvolutionFuncT>;

  // Helper struct combining the current schema version of each type and an
  // index into the schema evolution "map" below
  struct MapIndex {
    SchemaVersionT currentVersion;
    size_t index;
    constexpr static size_t NoEvolutionAvailable = -1u;
  };

  // The map that holds the current version for each type that is known to the
  // registry
  using VersionMapT = std::unordered_map<std::string, MapIndex>;
  // The "map" that holds all evolution functions
  using EvolutionMapT = std::vector<EvolFuncVersionMapT>;

  // Tag struct for marking collection types that do not need schema evolution.
  // Necessary due to the fact that we determine the current version from the
  // number of schema evolution functions we have
  struct NoSchemaEvolutionNecessaryT {};

public:
  /**
   * Enum to make it possible to prioritize evolution functions during
   * registration, making AutoGenerated lower priority than UserDefined
   */
  enum class Priority { AutoGenerated = 0, UserDefined = 1 };

  static constexpr auto NoSchemaEvolutionNecessary = NoSchemaEvolutionNecessaryT{};

  SchemaEvolution(const SchemaEvolution&) = delete;
  SchemaEvolution& operator=(const SchemaEvolution&) = delete;
  SchemaEvolution(SchemaEvolution&&) = delete;
  SchemaEvolution& operator=(SchemaEvolution&&) = delete;

  ~SchemaEvolution() = default;

  static SchemaEvolution& mutInstance();
  static SchemaEvolution const& instance();

  // TODO: Make this take a string_view
  podio::CollectionReadBuffers evolveBuffers(podio::CollectionReadBuffers oldBuffers, SchemaVersionT fromVersion,
                                             const std::string& collType) const;

  /**
   * Register an evoution function. Make the priority UserDefine dy default, so
   * that users do not have to add that argument, and instead make code
   * generation put the AutoGenerated value there
   *
   * NOTE: Currently necessary to fill the auto generated ones in the correct
   * order of fromVersion (becoming larger).
   */
  void registerEvolutionFunc(const std::string& collType, SchemaVersionT fromVersion,
                             const EvolutionFuncT& evolutionFunc, Priority priority = Priority::UserDefined);

  void registerEvolutionFunc(const std::string& collType, NoSchemaEvolutionNecessaryT);

  // Register the current version
  void registerCurrentVersion(const std::string& collType, SchemaVersionT currentVersion);

private:
  SchemaEvolution() = default;

  VersionMapT m_versionMapIndices{};
  EvolutionMapT m_evolutionFuncs{};
};

} // namespace podio

#endif // PODIO_SCHEMAEVOLUTION_H
