name: "Cache External Data"
description: "Caches external data that we fetch via CMake"
inputs:
  stack:
    description: The stack on which this is run
    required: True
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "STACK=$(echo ${{ inputs.stack }} | sed s':/:-:')" >> $GITHUB_ENV
    - uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/build/ExternalData
        key: external-data-${{ env.STACK }}-${{ env.NOW }}
        restore-keys: |
          external-data
