#!/usr/bin/env python3
"""Tiny script to ingest a json string and dump it as a yaml string"""

import argparse
import json
import sys

import yaml


def main():
    """Main, read json from stdin and dump yaml to stdout"""
    parser = argparse.ArgumentParser(
        description="Convert JSON (from stdin) to YAML (to stdout).",
    )
    parser.parse_args()

    input_data = sys.stdin.read()
    model_def = json.loads(input_data)
    print(yaml.dump(model_def, sort_keys=False, default_flow_style=False))


if __name__ == "__main__":
    main()
