name: edm4hep

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        LCG: ["LCG_106/x86_64-el9-gcc13-opt",
              "dev4/x86_64-el9-gcc14-opt",
              "dev3/x86_64-el9-clang16-opt"]
    steps:
      - uses: actions/checkout@v4
        with:
          path: podio
      - uses: actions/checkout@v4
        with:
          repository: key4hep/EDM4hep
          path: edm4hep
      - uses: actions/checkout@v4
        with:
          repository: catchorg/Catch2
          path: catch2
          ref: v3.4.0
      - uses: cvmfs-contrib/github-action-cvmfs@v4
      - uses: aidasoft/run-lcg-view@v4
        with:
          release-platform: ${{ matrix.LCG }}
          run: |
            STARTDIR=$(pwd)
            echo "::group::Build Catch2"
            cd $STARTDIR/catch2
            mkdir build && cd build
            cmake -DCMAKE_CXX_STANDARD=20 -DCMAKE_INSTALL_PREFIX=../install -G Ninja ..
            ninja -k0 install
            export CMAKE_PREFIX_PATH=$STARTDIR/catch2/install:$CMAKE_PREFIX_PATH
            echo "::endgroup::"
            echo "::group::Build podio"
            cd $STARTDIR/podio
            mkdir build && cd build
            cmake -DENABLE_SIO=ON \
              -DENABLE_JULIA=ON \
              -DENABLE_DATASOURCE=ON \
              -DENABLE_RNTUPLE=ON \
              -DCMAKE_INSTALL_PREFIX=../install \
              -DCMAKE_CXX_STANDARD=20 \
              -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always -Werror -Wno-error=deprecated-declarations " \
              -DUSE_EXTERNAL_CATCH2=ON \
              -DBUILD_TESTING=OFF\
              -G Ninja ..
            ninja -k0
            echo "::endgroup::"
            echo "::group::Test and install podio"
            ctest --output-on-failure
            ninja install
            cd $STARTDIR/podio
            source init.sh && source env.sh
            echo "::endgroup::"
            echo "::group::Build and test EDM4hep"
            cd $STARTDIR/edm4hep
            mkdir build && cd build
            cmake -DCMAKE_CXX_STANDARD=20 \
              -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always " \
              -DUSE_EXTERNAL_CATCH2=ON \
              -G Ninja ..
            ninja -k0
            ctest --output-on-failure
            echo "::endgroup::"
