name: mac

on: [push, pull_request]

jobs:
  compile:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        LCG: ["LCG_98python3/x86_64-mac1015-clang110-opt",
              "LCG_97apython3/x86_64-mac1015-clang110-opt"]
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
      with:
        cvmfs_repositories: 'sft.cern.ch,geant4.cern.ch'
    - uses: aidasoft/run-lcg-view@v2
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          /bin/bash .github/scripts/compile_and_test.sh
