name: mac

on: [push, pull_request]

jobs:
  compile:
    runs-on: macos-10.15
    strategy:
      matrix:
        LCG: ["LCG_98python3/x86_64-mac1015-clang110-opt","LCG_97apython3/x86_64-mac1015-clang110-opt"]
    steps:
    - uses: actions/checkout@v2
    - name: Install CVMFS
      run: |
        brew install ninja
        brew cask install osxfuse
        curl -L -o cvmfs-2.7.3.pkg https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.7.3/cvmfs-2.7.3.pkg
        sudo installer -package cvmfs-2.7.3.pkg -target /
        wget --no-check-certificate https://lcd-data.web.cern.ch/lcd-data/CernVM/default.local
        sudo mv default.local /etc/cvmfs/default.local
        sudo cvmfs_config setup
        brew cask install gfortran
        brew cask install xquartz
    - name: Mount CVMFS
      run: |
        mkdir -p /Users/Shared/cvmfs/sft.cern.ch
        mkdir -p /Users/Shared/cvmfs/geant4.cern.ch
        sudo mount -t cvmfs sft.cern.ch /Users/Shared/cvmfs/sft.cern.ch
        sudo mount -t cvmfs geant4.cern.ch /Users/Shared/cvmfs/geant4.cern.ch
        ls /Users/Shared/cvmfs/sft.cern.ch
        ls /Users/Shared/cvmfs/geant4.cern.ch
    - name: Compile and test
      run: |
        source /Users/Shared/cvmfs/sft.cern.ch/lcg/views/${{ matrix.LCG }}/setup.sh
        mkdir build install
        cd build
        cmake  -GNinja -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_CXX_STANDARD=17  -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always " ..
        ninja -k 0
        ninja install
        ctest --output-on-failure
