name: sanitizers

on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc10, clang10]
        # Since Leak is usually part of Address, we do not run it separately in
        # CI. Keeping Address and Undefined separate for easier debugging
        sanitizer: [Thread,
                    Address,
                    Undefined]
        include:
          # Memory sanitizer is not available for gcc
          - compiler: clang10
            sanitizer: MemoryWithOrigin
    steps:
      - uses: actions/checkout@v2
      - uses: cvmfs-contrib/github-action-cvmfs@v2
      - uses: aidasoft/run-lcg-view@v2
        with:
          release-platform: LCG_99/x86_64-centos7-${{ matrix.compiler }}-opt
          run: |
            set -x
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug \
              -DUSE_SANITIZER=${{ matrix.sanitizer }} \
              -DCMAKE_CXX_STANDARD=17 \
              -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always " \
              -DUSE_EXTERNAL_CATCH2=OFF \
              -DENABLE_SIO=ON \
              -G Ninja ..
            ninja -k0
            ctest --output-on-failure
