name: sio_io

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ILCSoft: ["lcg/97/nightly/x86_64-centos7-gcc9-opt"]
    steps:
    - uses: actions/checkout@v2
    - name: Install CVMFS
      run: |
        wget --no-check-certificate https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
        sudo dpkg -i cvmfs-release-latest_all.deb
        sudo apt-get update
        sudo apt-get install cvmfs cvmfs-config-default
        wget --no-check-certificate https://lcd-data.web.cern.ch/lcd-data/CernVM/default.local
        sudo mkdir -p /etc/cvmfs
        sudo mv default.local /etc/cvmfs/default.local
        sudo cvmfs_config setup
        ls /cvmfs/sft.cern.ch
        ls /cvmfs/geant4.cern.ch
        ls /cvmfs/clicdp.cern.ch
    - name: Start container
      run: |
        docker run -it --name CI_container -v /home/runner/work/podio/podio:/Package -e VIEW=${{ matrix.ILCSoft }} -e USE_SIO=ON -v /cvmfs:/cvmfs -d clicdp/cc7-lcg /bin/bash
    - name: Compile and test
      run: |
        docker exec CI_container /bin/bash -c "./Package/.github/scripts/compile_and_test.sh"
