name: sio_io

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ILCSoft: ["lcg/97/nightly/x86_64-centos7-gcc9-opt"]
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - name: Start container
      run: |
        docker run -it --privileged --name CI_container -v /home/runner/work/podio/podio:/Package -e VIEW=${{ matrix.ILCSoft }} -e USE_SIO=ON -v /cvmfs:/cvmfs:shared -d ghcr.io/aidasoft/centos7:latest /bin/bash
    - name: Compile and test
      run: |
        docker exec CI_container /bin/bash -c "./Package/.github/scripts/compile_and_test.sh"
