name: sio_io

on: [push, pull_request]

jobs:
  ilcsoft_nightlies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        LCG: ["LCG_99/x86_64-centos7-gcc10-opt",
              "LCG_99/x86_64-ubuntu2004-gcc9-opt"]
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: aidasoft/run-lcg-view@v2
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          USE_SIO=ON /bin/bash .github/scripts/compile_and_test.sh

  mac-os:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
      with:
        cvmfs_repositories: 'sft.cern.ch,geant4.cern.ch'
    - uses: aidasoft/run-lcg-view@v2
      with:
       release-platform: LCG_99/x86_64-mac1015-clang120-opt
       run: |
         USE_SIO=ON /bin/bash .github/scripts/compile_and_test.sh
